// Plantillas de patologías oncológicas genitourinarias
// Cada campo: { id, label, tipo: 'text'|'number'|'date'|'select'|'boolean'|'textarea', opciones: [] }

const CAMPOS_COMUNES = [
  { id: 'historia_clinica', label: 'ID / Historia clínica', tipo: 'text' },
  { id: 'nombre', label: 'Nombre completo', tipo: 'text' },
  { id: 'fecha_nacimiento', label: 'Fecha de nacimiento', tipo: 'date' },
  { id: 'edad', label: 'Edad al diagnóstico', tipo: 'number' },
  { id: 'sexo', label: 'Sexo', tipo: 'select', opciones: ['Masculino', 'Femenino'] },
  { id: 'institucion', label: 'Institución', tipo: 'text' },
  { id: 'medico', label: 'Médico tratante', tipo: 'text' },
  { id: 'fecha_registro', label: 'Fecha de registro', tipo: 'date' },
];

const PLANTILLAS = {
  pene: {
    nombre: 'Cáncer de Pene',
    cie10: 'C60',
    color: '#c0392b',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'select', opciones: ['C60.0', 'C60.1', 'C60.2', 'C60.8', 'C60.9'] },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Carcinoma escamocelular', 'Verrucoso', 'Basaloide', 'Sarcomatoide', 'Otro'] },
      { id: 'grado', label: 'Grado diferenciación', tipo: 'select', opciones: ['G1 bien diferenciado', 'G2 moderado', 'G3 pobremente diferenciado'] },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['Tis', 'Ta', 'T1a', 'T1b', 'T2', 'T3', 'T4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'N2', 'N3', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1', 'Mx'] },
      { id: 'procedimiento', label: 'Procedimiento realizado', tipo: 'select', opciones: ['Circuncisión', 'Glansectomía parcial', 'Penectomía parcial', 'Penectomía total', 'Linfadenectomía inguinal bilateral', 'Quimioterapia', 'Radioterapia', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'estudios_extension', label: 'Estudios de extensión', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Adenopatías', 'Metástasis pulmonares', 'Metástasis regionales', 'Metástasis a distancia', 'Otro'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia local', 'Metástasis', 'Fallecido', 'Perdido seguimiento'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  prostata: {
    nombre: 'Cáncer de Próstata',
    cie10: 'C61',
    color: '#2980b9',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'text', default: 'C61' },
      { id: 'psa_diagnostico', label: 'PSA al diagnóstico (ng/mL)', tipo: 'number' },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Adenocarcinoma acinar', 'Ductal', 'Neuroendocrino', 'Otro'] },
      { id: 'gleason', label: 'Gleason Score', tipo: 'select', opciones: ['6 (3+3)', '7 (3+4)', '7 (4+3)', '8 (4+4)', '9 (4+5)', '9 (5+4)', '10 (5+5)'] },
      { id: 'isup', label: 'Grupo de grado ISUP', tipo: 'select', opciones: ['1', '2', '3', '4', '5'] },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['T1a', 'T1b', 'T1c', 'T2a', 'T2b', 'T2c', 'T3a', 'T3b', 'T4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1a', 'M1b', 'M1c', 'Mx'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Prostatectomía radical robótica', 'Prostatectomía radical abierta', 'Braquiterapia', 'EBRT', 'Hormonoterapia', 'Vigilancia activa', 'Crioterapia', 'HIFU', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'margenes', label: 'Márgenes quirúrgicos', tipo: 'select', opciones: ['Negativos', 'Positivos focales', 'Positivos extensos', 'No aplica'] },
      { id: 'extension_extraprost', label: 'Extensión extraprostática', tipo: 'select', opciones: ['No', 'Sí', 'No aplica'] },
      { id: 'invasion_vs', label: 'Invasión vesículas seminales', tipo: 'select', opciones: ['No', 'Sí', 'No aplica'] },
      { id: 'psa_post', label: 'PSA postoperatorio (ng/mL)', tipo: 'number' },
      { id: 'gammagrafia', label: 'Gammagrafía ósea', tipo: 'select', opciones: ['No realizada', 'Sin alteraciones', 'Lesiones sospechosas', 'Metástasis óseas'] },
      { id: 'psma_pet', label: 'PSMA PET/CT', tipo: 'select', opciones: ['No realizado', 'Negativo', 'Positivo local', 'Positivo ganglionar', 'Positivo a distancia'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia bioquímica', 'Recurrencia local', 'Metástasis', 'Resistente a castración', 'Fallecido'] },
      { id: 'psa_seguimiento', label: 'PSA en seguimiento (ng/mL)', tipo: 'number' },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  vejiga: {
    nombre: 'Cáncer de Vejiga',
    cie10: 'C67',
    color: '#8e44ad',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'select', opciones: ['C67.0','C67.1','C67.2','C67.3','C67.4','C67.5','C67.6','C67.7','C67.8','C67.9'] },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Carcinoma urotelial', 'Carcinoma escamocelular', 'Adenocarcinoma', 'Carcinoma de células pequeñas', 'Otro'] },
      { id: 'grado_who', label: 'Grado WHO 2004', tipo: 'select', opciones: ['Bajo grado', 'Alto grado'] },
      { id: 'invasion_muscular', label: 'Invasión muscular (MIBC)', tipo: 'boolean' },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['Ta', 'Tis', 'T1', 'T2a', 'T2b', 'T3a', 'T3b', 'T4a', 'T4b', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'N2', 'N3', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1a', 'M1b', 'Mx'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['RTU vejiga', 'Cistectomía radical', 'Cistectomía parcial', 'QT intravesical BCG', 'Quimioterapia sistémica', 'Inmunoterapia', 'Radioterapia', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'derivacion', label: 'Derivación urinaria', tipo: 'select', opciones: ['No aplica', 'Conducto ileal', 'Neovejiga ortotópica', 'Ureterostomía cutánea'] },
      { id: 'recurrencia_previa', label: 'Recurrencia previa', tipo: 'boolean' },
      { id: 'num_recurrencias', label: 'Número de recurrencias', tipo: 'number' },
      { id: 'tac_torax_abdomen', label: 'TAC tórax/abdomen/pelvis', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Adenopatías', 'Metástasis', 'Hidronefrosis', 'Otro'] },
      { id: 'cistoscopia_seguimiento', label: 'Cistoscopia de seguimiento', tipo: 'select', opciones: ['No realizada', 'Sin recurrencia', 'Recurrencia Ta', 'Recurrencia T1', 'Recurrencia T2+'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia', 'Progresión', 'Metástasis', 'Fallecido'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  rinon: {
    nombre: 'Cáncer de Riñón',
    cie10: 'C64',
    color: '#27ae60',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'text', default: 'C64' },
      { id: 'lateralidad', label: 'Lateralidad', tipo: 'select', opciones: ['Derecho', 'Izquierdo', 'Bilateral'] },
      { id: 'tamano', label: 'Tamaño tumor (cm)', tipo: 'number' },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Células claras', 'Papilar tipo 1', 'Papilar tipo 2', 'Cromófobo', 'Oncocitoma', 'Conductos colectores', 'Translocación Xp11', 'Otro'] },
      { id: 'grado_isup', label: 'Grado ISUP/Fuhrman', tipo: 'select', opciones: ['G1', 'G2', 'G3', 'G4'] },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['T1a', 'T1b', 'T2a', 'T2b', 'T3a', 'T3b', 'T3c', 'T4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1', 'Mx'] },
      { id: 'imdc', label: 'Grupo pronóstico IMDC', tipo: 'select', opciones: ['Favorable', 'Intermedio', 'Pobre', 'No aplica'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Nefrectomía radical laparoscópica', 'Nefrectomía radical abierta', 'Nefrectomía parcial laparoscópica', 'Nefrectomía parcial robótica', 'Ablación por radiofrecuencia', 'Crioablación', 'Vigilancia activa', 'Terapia sistémica', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'trombosis_venosa', label: 'Trombosis venosa', tipo: 'select', opciones: ['No', 'Vena renal', 'VCI infrahepática', 'VCI suprahepática', 'Aurícula derecha'] },
      { id: 'tac_torax', label: 'TAC tórax', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Metástasis pulmonares', 'Adenopatías', 'Otro'] },
      { id: 'tac_abdomen', label: 'TAC abdomen', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Recurrencia local', 'Metástasis hepáticas', 'Adenopatías', 'Otro'] },
      { id: 'terapia_sistemica', label: 'Terapia sistémica 1ª línea', tipo: 'select', opciones: ['No indicada', 'Sunitinib', 'Pazopanib', 'Cabozantinib', 'Nivolumab+Ipilimumab', 'Pembrolizumab+Axitinib', 'Nivolumab+Cabozantinib', 'Otro'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia local', 'Metástasis', 'En terapia sistémica', 'Fallecido'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  testiculo: {
    nombre: 'Cáncer de Testículo',
    cie10: 'C62',
    color: '#d35400',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'select', opciones: ['C62.0', 'C62.1', 'C62.9'], default: 'C62.9' },
      { id: 'lateralidad', label: 'Lateralidad', tipo: 'select', opciones: ['Derecho', 'Izquierdo'] },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Seminoma clásico', 'Seminoma espermatocítico', 'Carcinoma embrionario', 'Teratoma maduro', 'Teratoma inmaduro', 'Tumor del saco vitelino', 'Coriocarcinoma', 'Tumor mixto de células germinales'] },
      { id: 'tipo_tumor', label: 'Tipo tumor', tipo: 'select', opciones: ['Seminoma puro', 'No seminoma', 'Mixto'] },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'afp', label: 'AFP al diagnóstico (ng/mL)', tipo: 'number' },
      { id: 'bhcg', label: 'B-HCG al diagnóstico (mUI/mL)', tipo: 'number' },
      { id: 'ldh', label: 'LDH al diagnóstico (U/L)', tipo: 'number' },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['pT1a', 'pT1b', 'pT2', 'pT3', 'pT4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'N2', 'N3', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1a', 'M1b', 'Mx'] },
      { id: 'tnm_s', label: 'S (marcadores)', tipo: 'select', opciones: ['S0', 'S1', 'S2', 'S3', 'Sx'] },
      { id: 'estadio_igcccg', label: 'Estadio clínico IGCCCG', tipo: 'select', opciones: ['IA', 'IB', 'IS', 'IIA', 'IIB', 'IIC', 'IIIA', 'IIIB', 'IIIC'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Orquiectomía radical', 'Vigilancia activa', 'QT BEP x1', 'QT BEP x3', 'QT BEP x4', 'QT EP x4', 'Radioterapia retroperitoneal', 'LRPR', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'afp_post', label: 'AFP postorquiectomía (ng/mL)', tipo: 'number' },
      { id: 'bhcg_post', label: 'B-HCG postorquiectomía (mUI/mL)', tipo: 'number' },
      { id: 'tac_general', label: 'TAC tórax/abdomen/pelvis', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Adenopatías retroperitoneales <2cm', 'Adenopatías 2–5cm', 'Masa >5cm', 'Metástasis pulmonares', 'Otro'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia', 'En quimioterapia', 'Fallecido'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  ureter: {
    nombre: 'Urotelial Alto',
    cie10: 'C65-C66',
    color: '#16a085',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'select', opciones: ['C65 — Pelvis renal', 'C66 — Uréter'], default: 'C65 — Pelvis renal' },
      { id: 'localizacion', label: 'Localización', tipo: 'select', opciones: ['Pelvis renal', 'Uréter proximal', 'Uréter medio', 'Uréter distal', 'Multifocal'] },
      { id: 'lateralidad', label: 'Lateralidad', tipo: 'select', opciones: ['Derecho', 'Izquierdo', 'Bilateral'] },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Carcinoma urotelial', 'Carcinoma escamocelular', 'Adenocarcinoma', 'Otro'] },
      { id: 'grado', label: 'Grado', tipo: 'select', opciones: ['Bajo grado', 'Alto grado'] },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['Ta', 'Tis', 'T1', 'T2', 'T3', 'T4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'N2', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1', 'Mx'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Nefroureterectomía radical laparoscópica', 'Nefroureterectomía radical abierta', 'Resección segmentaria', 'Ureteroscopia + ablación', 'Quimioterapia', 'Inmunoterapia', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'tac_uro', label: 'TAC urotomografía', tipo: 'select', opciones: ['No realizada', 'Sin alteraciones', 'Defecto de llenado', 'Hidronefrosis', 'Metástasis', 'Otro'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia vesical', 'Recurrencia ureteral', 'Metástasis', 'Fallecido'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  adrenal: {
    nombre: 'Cáncer Adrenal',
    cie10: 'C74',
    color: '#6c3483',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'select', opciones: ['C74.0 — Corteza suprarrenal', 'C74.1 — Médula suprarrenal', 'C74.9 — NE'], default: 'C74.0 — Corteza suprarrenal' },
      { id: 'lateralidad', label: 'Lateralidad', tipo: 'select', opciones: ['Derecho', 'Izquierdo', 'Bilateral'] },
      { id: 'tamano', label: 'Tamaño tumor (cm)', tipo: 'number' },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Carcinoma corticosuprarrenal', 'Feocromocitoma maligno', 'Neuroblastoma', 'Paraganglioma maligno', 'Otro'] },
      { id: 'ki67', label: 'Índice Ki-67 (%)', tipo: 'number' },
      { id: 'sindrome_cushing', label: 'Síndrome de Cushing', tipo: 'boolean' },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['T1', 'T2', 'T3', 'T4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1', 'Mx'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Adrenalectomía laparoscópica', 'Adrenalectomía abierta', 'Adrenalectomía robótica', 'Mitotano', 'Quimioterapia', 'Radioterapia', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'tac_torax_abdomen', label: 'TAC tórax/abdomen', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Recurrencia local', 'Metástasis pulmonares', 'Metástasis hepáticas', 'Adenopatías', 'Otro'] },
      { id: 'pet_ct', label: 'PET/CT', tipo: 'select', opciones: ['No realizado', 'Negativo', 'Positivo local', 'Positivo ganglionar', 'Positivo a distancia'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia local', 'Metástasis', 'En tratamiento', 'Fallecido'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  escroto: {
    nombre: 'Cáncer de Escroto',
    cie10: 'C63.2',
    color: '#784212',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'text', default: 'C63.2' },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Carcinoma escamocelular', 'Carcinoma basocelular', 'Melanoma', 'Sarcoma', 'Enfermedad de Paget', 'Otro'] },
      { id: 'grado', label: 'Grado diferenciación', tipo: 'select', opciones: ['G1 bien diferenciado', 'G2 moderado', 'G3 pobremente diferenciado'] },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['T1', 'T2', 'T3', 'T4', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'N2', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1', 'Mx'] },
      { id: 'extension_local', label: 'Extensión local', tipo: 'select', opciones: ['Limitado a escroto', 'Compromiso testicular', 'Compromiso perineal', 'Compromiso inguinal', 'Otro'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Escisión local amplia', 'Hemiescrotectomía', 'Escrotectomía total', 'Linfadenectomía inguinal', 'Radioterapia', 'Quimioterapia', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'tac_abdomen_pelvis', label: 'TAC abdomen/pelvis', tipo: 'select', opciones: ['No realizado', 'Sin alteraciones', 'Adenopatías inguinales', 'Adenopatías pélvicas', 'Metástasis', 'Otro'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia local', 'Metástasis', 'Fallecido', 'Perdido seguimiento'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  },

  uretra: {
    nombre: 'Cáncer de Uretra',
    cie10: 'C68.0',
    color: '#1a5276',
    campos: [
      ...CAMPOS_COMUNES,
      { id: 'cie10', label: 'Código CIE-10', tipo: 'text', default: 'C68.0' },
      { id: 'localizacion', label: 'Localización', tipo: 'select', opciones: ['Uretra anterior/distal', 'Uretra posterior/proximal', 'Toda la uretra'] },
      { id: 'fecha_diagnostico', label: 'Fecha diagnóstico', tipo: 'date' },
      { id: 'histologia', label: 'Histología', tipo: 'select', opciones: ['Carcinoma urotelial', 'Carcinoma escamocelular', 'Adenocarcinoma', 'Carcinoma de células claras', 'Otro'] },
      { id: 'tnm_t', label: 'T (TNM)', tipo: 'select', opciones: ['T1', 'T2', 'T3', 'T4a', 'T4b', 'Tx'] },
      { id: 'tnm_n', label: 'N (TNM)', tipo: 'select', opciones: ['N0', 'N1', 'N2', 'Nx'] },
      { id: 'tnm_m', label: 'M (TNM)', tipo: 'select', opciones: ['M0', 'M1', 'Mx'] },
      { id: 'procedimiento', label: 'Procedimiento', tipo: 'select', opciones: ['Resección transuretral', 'Uretrectomía distal', 'Uretrectomía total', 'Cistouretroprostectomía', 'Quimioterapia', 'Radioterapia', 'Quimiorradioterapia', 'Otro'] },
      { id: 'fecha_procedimiento', label: 'Fecha procedimiento', tipo: 'date' },
      { id: 'cistoscopia', label: 'Cistoscopia', tipo: 'select', opciones: ['No realizada', 'Sin alteraciones', 'Compromiso vesical', 'Otro'] },
      { id: 'tac_rmn_pelvis', label: 'TAC/RMN pelvis', tipo: 'select', opciones: ['No realizada', 'Sin alteraciones', 'Compromiso local', 'Adenopatías', 'Metástasis', 'Otro'] },
      { id: 'estado_actual', label: 'Estado actual', tipo: 'select', opciones: ['Libre de enfermedad', 'Recurrencia local', 'Metástasis', 'Fallecido', 'Perdido seguimiento'] },
      { id: 'proximo_seguimiento', label: 'Próximo seguimiento', tipo: 'date' },
      { id: 'observaciones', label: 'Observaciones', tipo: 'textarea' },
    ]
  }
};
